### ISSUE TITLE
video request

### ISSUE THREAD

**Issue by CheetoTrump** [Kudaes/ADPT#1]
Can you make a video of you showing this because i might be retarded or something but when running your 1:1 commands it is not writing to the other project files what so ever

**Comment by Kudaes** [comment]
Hi @CheetoTrump,
Don't think you are retarded, probably it's the tool failing for some reason xD What dll are you trying to trace/proxy? Have you tried using Pe-Bear to analyze the dll, looking for its exports? 

This behaviour that you are commenting happened to me when I tried to run the tool over a DLL with no exports (for example, a dll used to store static resources like images and so), maybe that's what is going on in your case as well.

**Comment by CheetoTrump** [comment]
> Hi @CheetoTrump, Don't think you are retarded, probably it's the tool failing for some reason xD What dll are you trying to trace/proxy? Have you tried using Pe-Bear to analyze the dll, looking for its exports?
> 
> This behaviour that you are commenting happened to me when I tried to run the tool over a DLL with no exports (for example, a dll used to store static resources like images and so), maybe that's what is going on in your case as well.

I tried different dlls and added checks etc, ill send the upate

also the dll had 3 exports

**Comment by CheetoTrump** [comment]
[elo.json](https://github.com/user-attachments/files/15576540/elo.json)

couldnt upload .rs directly so just rename to .rs

**Comment by Kudaes** [comment]
Is your dll present on a default windows installation so I can try to run the tool on it? May you send me the exact command you are typing to generate the trace/proxy dlls?

**Comment by CheetoTrump** [comment]
generator.exe -m trace -p C:\Windows\System32\adhapi.dll

dumpbin export of the dll

Dump of file C:\Windows\System32\adhapi.dll
        1000 .pdata
File Type: DLLrdata
        1000 .reloc
  Section contains the following exports for AdhApi.dll
        7000 .text
    00000000 characteristicsest> du
    8AC114AE time date stamp
        0.00 version
           1 ordinal base
           7 number of functions
           7 number of names

    ordinal hint RVA      name

          1    0 000019A0 AdhEngineClose
          2    1 00001790 AdhEngineOpen
          3    2 00002570 AdhGetConfig
          4    3 00002800 AdhGetEvidenceCollectorResult
          5    4 00001EC0 AdhStatusEventSubscribe
          6    5 000022F0 AdhStatusEventUnsubscribe
          7    6 00001120 DllMain

  Summary

        1000 .data
        1000 .pdata
        2000 .rdata
        1000 .reloc
        1000 .rsrc
        3000 .text
        
        after running no files were written

**Comment by Kudaes** [comment]
```
> generator.exe -m trace -p C:\Windows\System32\adhapi.dll
[+] Process completed.
```
It is working perfectly on several VMs that I have. Do you manage to reach the "Process completed" message when you run the command?
Any particularities about your system (SO version, special restrictions...) that might give me a clue?

**Comment by Kudaes** [comment]
Any update on this issue?
